feat: allow ebs launch template encryption
cloudposse/terraform-aws-eks-node-group pull request #36
Opened 2020-10-08 20:33 UTC by dotCipher

## what
* Surface variable for boolean flag of `launch_template_disk_encryption`
* Use `launch_template_disk_encryption` to flip flag of generated `launch_template.ebs.encryption`

## why
* Allow EBS encryption 

## references
* Closes #35

2020-10-13 21:16 UTC, Gowiem commented
/rebuild-readme

2020-10-13 21:17 UTC, Gowiem commented
/test all

2020-10-13 21:30 UTC, Gowiem commented
/test all

2020-10-13 21:35 UTC, Gowiem commented
/terraform-fmt

2020-10-13 21:44 UTC, Gowiem commented
/test all

2020-10-13 21:49 UTC, aknysh commented on variables.tf
> +  description = "Enable disk encryption if not providing `launch_template_name` of an existing template."
```suggestion
  description = "Enable disk encryption for the created launch template (if we aren't provided with an existing launch template)"
```

2020-10-13 21:49 UTC, aknysh reviewed
see comments

2020-10-13 22:19 UTC, dotCipher commented
Cool, thanks for the review!

2020-10-14 00:55 UTC, aknysh commented
/rebuild-readme

2020-10-14 00:57 UTC, aknysh commented
/terraform-fmt

2020-10-14 00:57 UTC, aknysh commented
/test all

2020-10-14 01:04 UTC, aknysh commented on launch-template.tf
> +      encrypted   = var.launch_template_disk_encryption
```suggestion
      encrypted   = var.launch_template_disk_encryption_enabled
```

2020-10-14 01:05 UTC, aknysh requested changes
please see comments

2020-10-14 01:18 UTC, dotCipher commented on launch-template.tf
> +      encrypted   = var.launch_template_disk_encryption
Ah right my bad :)

2020-10-14 01:18 UTC, dotCipher commented
/rebuild-readme

2020-10-14 01:52 UTC, aknysh commented
/rebuild-readme

2020-10-14 01:53 UTC, aknysh commented
/test all

2020-10-14 02:21 UTC, aknysh approved these changes
thanks @dotCipher

2020-10-14 02:21 UTC, merged